### ISSUE TITLE
 Consider Adding Minimum Stability Constraint to Composer Config

### ISSUE THREAD

**Issue by namumakwembo** [woosignal/laravel-fcm-notify#1]
I encountered an error while trying to install the package using the composer require command:

`Could not find a version of package veskodigital/laravel-fcm-channel matching your minimum-stability (stable). Require it with an explicit version constraint allowing its desired stability.
`

It appears that the package does not have a minimum stability constraint defined in its composer.json file.

I suggest adding a minimum stability constraint to the composer.json file of the package. This would provide clearer guidance to users about which stability versions of the package are available and supported.

**Comment by agordn52** [comment]
Hi @namumakwembo,

Thanks for highlighting this, I've just added the change.
This package will need updating though because it's using the old Firebase API.

I'll work on this next week.
